[project]
name = "cryo-sql-mcp"
version = "0.1.0"
description = "MCP server for Cryo + SQL"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
 "mcp[cli]>=1.4.1",
 "requests>=2.32.3",
]
